name: CI

on:
  push:
    branches:
      - master

  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  common:
    name: Common
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run common/JVM tests
        run: ./gradlew :shared:jvmTest


  android:
    name: Android
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run Android tests
        run: ./gradlew :shared:testAndroidHostTest :androidApp:testDebugUnitTest


  desktop:
    name: Desktop
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run Desktop tests
        run: ./gradlew :desktopApp:test


  js:
    name: Web JS
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run JS tests
        run: ./gradlew :webApp:jsBrowserTest


  wasm:
    name: Web WASM
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run WASM tests
        run: ./gradlew :webApp:wasmJsBrowserTest


  ios:
    name: iOS
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run iOS tests
        run: ./gradlew :shared:iosSimulatorArm64Test
